# Generated by Django 2.2.24 on 2021-09-28 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='项目名称')),
                ('description', models.CharField(blank=True, max_length=1024, null=True, verbose_name='描述')),
            ],
        ),
    ]
