# Generated by Django 2.2.24 on 2021-10-18 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paltform', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='childMoudle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='子模块')),
                ('description', models.CharField(blank=True, max_length=1024, null=True, verbose_name='描述')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='paltform.Project', verbose_name='所属项目')),
            ],
        ),
    ]
