# Generated by Django 2.2.24 on 2021-10-18 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paltform', '0002_childmoudle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childmoudle',
            name='project',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='paltform.Project', verbose_name='所属项目'),
        ),
    ]
